fprintf('>y=loadaudio(''F6.baroque'',''au'',8);\n');
pause
y=loadaudio('F6.baroque','au',8);
pause
fprintf('>plot(y);\n');
pause
plot(y);
pause
fprintf('>plot(y(20000:20500));\n');
pause
plot(y(20000:20500));
pause
fprintf('>N=length(y)\n');
pause
N=length(y)
pause
fprintf('>Fs=22050\n');
pause
Fs=22050
pause
fprintf('>omega=[0:N-1]*Fs/N;\n');
pause
omega=[0:N-1]*Fs/N;
pause
fprintf('>Nmax=floor(N/4)\n');
pause
Nmax=floor(N/4)
pause
fprintf('>tildec=fft(y);\n');
pause
tildec=fft(y);
pause
fprintf('>plot(omega(1:Nmax),abs(tildec(1:Nmax))/N);\n');
pause
plot(omega(1:Nmax),abs(tildec(1:Nmax))/N);
pause
fprintf('>semilogy(omega(1:Nmax),abs(tildec(1:Nmax))/N);\n');
pause
semilogy(omega(1:Nmax),abs(tildec(1:Nmax))/N);
pause
